<?php
$file = __FILE__;
$modifytime = date ("M. j Y.", filemtime($file));
$age = coppa_check(9, 12, 1967);

/***********************************************************************
Name: coppa_check($day, $month, $year)
Author: Jason DeFillippo <jason@mykungfu.com>
Description: This is a down and dirty COPPA age verifier. This function takes 3 args. A birthday, a birthmonth and a birthyear and returns the users actual age if it's good and false if it's non-compliant. Throw this into a general include file and slap it in your library and you won't have to worry if you're letting any kids in. This is an important issue since it's illegal to gather user data if the person is under 13 years old.
***********************************************************************/
function coppa_check($day, $month, $year){
	//check to see if we have a 2 digit year. If so convert it to standard 4 char format
	//if (strlen($year) == 2){$year = "19" . $year;}    
	//First do a check to see if we have a good date
	$isgood = checkdate($month, $day, $year);
	//dump it if the date is bad...
	if ($isgood != 1){
		return FALSE;
	}
	//do some date to timestamp conversions
	$birthdate = mktime(0,0,0,$month,$day,$year);
	$today = time();
	//now do them back so we can get some different info.
	$old_date = getdate($birthdate);
	$current_date = getdate($today);
	//error check to make sure the date's not in the future
	if ($current_date[year] < $year){return FALSE;}
	//adjust for day of the month and get final age.
	if ($current_date[yday] >= $old_date[yday]){
		$age = $current_date[year] - $year;
	}else{
		$age = ($current_date[year] - $year) -1;
	}
	//age range check
	//if ($age < 13 || $age > 120){
	//	return FALSE;
	//}
	//fallthru and spit back the actual age just for fun.
	return $age;
}//end coppa_check 
?>
<html>
<head>
<title>CV - Petri Laihonen</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF" text="#000000" link="#333333" vlink="#000000" alink="#FF6633">
<!-- 
#
#	Please do not use the coding in this CV as a reference to my coding.
#	It was generated by an online system several years ago, and I've never
#	Had time to redo it myself. IMHO Code in this page is horrendeous!!!!
#
-->
<table border=0 cellpadding=0 cellspacing=0>
  <tbody> 
  <tr> 
    <td width=34>&nbsp;</td>
    <td noWrap valign=top width=534> 
      <table border=0 cellpadding=0 cellspacing=0>
        <tbody> 
        <tr> 
          <td valign=top> <span 
            class=headerGrey><font face="Arial Narrow" size="6" color="#999999"><b>CV</b></font></span> 
          </td>
          <td valign=middle width=266> 
            <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif"><font size="4"><b>P</b></font><b>ETRI 
              <font size="4">L</font>AIHONEN </b></font></div>
          </td>
          <td width=7>&nbsp;</td>
          <td bgcolor=#CCCCCC valign=top width=1><img height=1 
            images/R1transparent_dot.gif" width=1></td>
          <td height=10 noWrap valign=top width=265> 
            <table border=0 cellpadding=0 cellspacing=0 width=266>
              <tbody> 
              <tr> 
                <td width=6>&nbsp;</td>
                <td valign=top>
                  <div align="right"><span class=header></span><br>
                    <br>
                        <font color="#666666" face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>Revised <?php echo $modifytime;?></b></font></div>
                </td>
              </tr>
              </tbody>
            </table>
          </td>
        </tr>
        </tbody>
      </table>
      <table cellpadding=0 cellspacing=0 height=24 width=533>
        <tbody> 
        <tr> 
          <td height=24 noWrap>&nbsp;</td>
        </tr>
        </tbody>
      </table>
      <!-- START PERSONAL INFORMATION -->
      <table bgcolor=#999999 border=0 cellpadding=1 cellspacing=0 width=534>
        <tbody> 
        <tr> 
          <td> 
            <table bgcolor=#999999 border=0 cellpadding=0 cellspacing=0 
            width=533>
              <tbody> 
              <tr> 
                <td height=24><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><img border=0 height=10 width=6 src="images/R1transparent_dot.gif">CONTACT 
                  INFORMATION</b></font></td>
              </tr>
			    <td align=right colspan=3 bgcolor="#FFFFFF"><br>
                </td>
              
            </table>
            <table bgcolor=#ffffff border=0 cellpadding=0 cellspacing=0 
            width=533>
              <tbody> 
              <tr> 
                <td bgcolor=#999999 colspan=7 height=1 noWrap><img 
                  border=0 height=1 
                  images/R1transparent_dot.gif" 
              width=1></td>
              </tr>
              <tr> 
                <td noWrap width=8><img border=0 height=1  width=1 src="images/R1transparent_dot.gif"></td>
                <td height=24 noWrap width=94><span 
                class=texts><font face="Verdana, Arial, Helvetica, sans-serif" size="2">First 
                  Name</font></span></td>
                <td width="160" bgcolor="#CCCCCC"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font>Petri</font></b></td>
                <td width="7"><img border=0 height=1  width=1 src="images/R1transparent_dot.gif"> 
                </td>
                <td height=24 noWrap width=105><span 
                class=texts><font size="2" face="Verdana, Arial, Helvetica, sans-serif">Last 
                  Name</font></span></td>
                <td height=24 noWrap width=153 bgcolor="#CCCCCC"><b><font size="2" face="Verdana, Arial, Helvetica, sans-serif"><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font>Laihonen</font></b></td>
                <td width="6"><img border=0 height=1  width=1 src="images/R1transparent_dot.gif"> 
                </td>
              </tr>
              <tr> 
                <td bgcolor=#999999 colspan=7 height=1 noWrap><img 
                  border=0 height=1 
                  images/R1transparent_dot.gif" 
              width=1></td>
              </tr>
              <tr> 
                <td width="8"><img border=0 height=1 
                  images/R1transparent_dot.gif" width=1></td>
                <td height=24 noWrap width=94><span 
                  class=texts><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Sex</font></span></td>
                <td width="160" bgcolor="#CCCCCC"><b><span class=texts><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font>Male</font></span></b></td>
                <td width="7"><img border=0 height=1  width=1 src="images/R1transparent_dot.gif"> 
                </td>
                <td height=24 noWrap width=105><span 
                  class=texts><font size="2" face="Verdana, Arial, Helvetica, sans-serif">Birth</font></span></td>
                <td height=24 noWrap width=153 bgcolor="#CCCCCC"><b><span class=texts><font size="2" face="Verdana, Arial, Helvetica, sans-serif"><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font>12 
                  / 09 / 1967</font></span></b></td>
                <td width="6"><img border=0 height=1  width=1 src="images/R1transparent_dot.gif"> 
                </td>
              </tr>
              <tr> 
                <td bgcolor=#999999 colspan=7 height=1 noWrap><img 
                  border=0 height=1 
                  images/R1transparent_dot.gif" 
              width=1></td>
              </tr>
              <tr> 
                <td width="8"><img border=0 height=1 
                  images/R1transparent_dot.gif" width=1></td>
                <td height=24 noWrap width=94><span 
                class=texts><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Address</font></span></td>
                <td width="160" bgcolor="#CCCCCC"><b><span class=texts><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font>1519 Bodenger Blvd. </font></span></b></td>
                <td width="7"><img border=0 height=1  width=1 src="images/R1transparent_dot.gif"> 
                </td>
                <td height=24 noWrap width=105><span 
                  class=texts><font size="2" face="Verdana, Arial, Helvetica, sans-serif">Zip</font></span></td>
                      <td height=24 noWrap width=153 bgcolor="#CCCCCC"><b><span class=texts><font size="2" face="Verdana, Arial, Helvetica, sans-serif"><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font>70114</font></span></b></td>
                      <td width="6"><img border=0 height=1  width=1 src="images/R1transparent_dot.gif"> 
                </td>
              </tr>
              <tr> 
                <td bgcolor=#999999 colspan=7 height=1 noWrap><img 
                  border=0 height=1 
                  images/R1transparent_dot.gif" 
              width=1></td>
              </tr>
              <tr> 
                <td width="8"><img border=0 height=1 
                  images/R1transparent_dot.gif" width=1></td>
                <td height=24 noWrap width=94><span 
                class=texts><font face="Verdana, Arial, Helvetica, sans-serif" size="2">City</font></span></td>
                <td width="160" bgcolor="#CCCCCC"><b><span class=texts><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font>New Orleans , 
                  LA</font></span></b></td>
                <td width="7"><img border=0 height=1  width=1 src="images/R1transparent_dot.gif"> 
                </td>
                <td height=24 noWrap width=105><span class=texts><font size="2" face="Verdana, Arial, Helvetica, sans-serif">Country</font></span></td>
                <td height=24 noWrap width=153 bgcolor="#CCCCCC"><b><span class=texts><font size="2" face="Verdana, Arial, Helvetica, sans-serif"><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font>USA</font></span></b></td>
                <td width="6"><img border=0 height=1  width=1 src="images/R1transparent_dot.gif"> 
                </td>
              </tr>
              <tr> 
                <td bgcolor=#999999 colspan=7 height=1 noWrap><img 
                  border=0 height=1 
                  images/R1transparent_dot.gif" 
              width=1></td>
              </tr>
              <tr> 
                <td width="8"><img border=0 height=1 
                  images/R1transparent_dot.gif" width=1></td>
                <td height=24 noWrap width=94><span 
                  class=texts><font face="Verdana, Arial, Helvetica, sans-serif" size="2">E-mail</font></span></td>
                  <td width="160" bgcolor="#CCCCCC"><b><a href="mailto:pietu@weblizards.net"><span class=texts><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font>pietu@weblizards.net</font></span></a></b></td>
                <td width="7"><img border=0 height=1  width=1 src="images/R1transparent_dot.gif"> 
                </td>
                <td height=24 noWrap width=105><span 
                class=texts><font size="2" face="Verdana, Arial, Helvetica, sans-serif">Phone</font></span></td>
                <td height=24 noWrap width=153 bgcolor="#CCCCCC"><b><span class=texts><font size="2" face="Verdana, Arial, Helvetica, sans-serif"><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font>+1 
                  504 343 1153</font></span></b></td>
                <td width="6"><img border=0 height=1  width=1 src="images/R1transparent_dot.gif"> 
                </td>
              </tr>
              <tr> 
                <td bgcolor=#999999 colspan=7 height=1 noWrap><img 
                  border=0 height=1 
                  images/R1transparent_dot.gif" 
              width=1></td>
              </tr>
			    <td align=right colspan=3 bgcolor="#FFFFFF">&nbsp;</td>
               
            </table>
          </td>
        </tr>
        </tbody>
      </table>
      <!-- END PERSONAL INFORMATION -->
      <font color="#FFFFFF">|</font> 
      <table cellpadding=0 cellspacing=0 height=24 width=533>
        <tr> 
          <td height=24 noWrap> 
            <table bgcolor=#999999 border=0 cellpadding=1 cellspacing=0 width=534>
              <tbody> 
              <tr> 
                <td> 
                  <table bgcolor=#999999 border=0 cellpadding=0 cellspacing=0 
            width=533>
                    <tbody> 
                    <tr> 
                      <td height=24><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
                  width=1><span 
            class=textWhtb><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font><font color="#FFFFFF">INTRODUCTION</font></b></span></font></td>
                    </tr>
                    </tbody> 
                  </table>
                  <table bgcolor=#ffffff border=0 cellpadding=0 cellspacing=0 
            width=533>
                    <tbody> 
                    <tr> 
                      <td bgcolor=#999999 colspan=3 height=1 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 
                  height=1 images/R1transparent_dot.gif" 
                  width=1></font></td>
                    </tr>
                    <tr> 
                      <td height=24 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
                  images/R1transparent_dot.gif" width=1 src="Jobline_fi_files/R1ViewCVSummary_files/R1transparent_dot.gif"></font></td>
                      <td><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><span class=texts><b>Short 
                        Intro</b></span></font></td>
                      <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
                  images/R1transparent_dot.gif" 
              width=1 src="Jobline_fi_files/R1ViewCVSummary_files/R1transparent_dot.gif"></font></td>
                    </tr>
                    <tr> 
                      <td noWrap width=4><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=12 width=4 src="images/R1transparent_dot.gif"></font></td>
                      <td bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class="texts">Extrovert Male, Age <?php echo $age;?>, Young. Born in Finland, Transplanted to US 1995, Married since 2002.
International and multiskilled.<br>
                      </span></font></td>
                      <td noWrap width=4><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
               width=1 src="Jobline_fi_files/R1ViewCVSummary_files/R1transparent_dot.gif"></font></td>
                    </tr>
                    <tr> 
                      <td colspan=3 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
                    </tr>
                    <tr> 
                      <td height=24 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=24 width=6 src="images/R1transparent_dot.gif"></font></td>
                      <td><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><span class=texts><b>Personal 
                        Intro</b></span></font></td>
                      <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
                    </tr>
                    <tr> 
                      <td noWrap width=4><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=12 width=4 src="images/R1transparent_dot.gif" ></font></td>
                      <td bgcolor=#CCCCCC> 
                        <table bgcolor=#CCCCCC border=0 cellpadding=3 cellspacing=0>
                          <tbody> 
                          <tr> 
                                  <td> <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Some Skills:<br>
                                      3D Animation, Networking, Web Design, Web
                                               Server Administration, Database
                                              Administration <br>
                                      Quickly capable of learning / adopting new 
                                      skills and techniques.<br>
                                      Strong English skills. ( Native Language, 
                                      Finnish ) <br>
                                      Strong skills for problem solving. (Hardware, 
                                      software and end users)<br>
                                      <br>
                                      Current Interests:<br>
                                      Wireless / Mobile technologies and content.<br>
                                      3D Modeling / Animation, Non-linear video 
                                      editing,<br>
                                      Web Design, Computer Systems support and 
                                      development.<br>
                                      Consulting for Media systems ( Hardware, 
                                      Design and Building ).<br>
                                  </span></font></p>
                            </td>
                          </tr>
                          </tbody> 
                        </table>
                      </td>
                      <td noWrap width=4><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=12 width=4
                  src="images/R1transparent_dot.gif" 
              ></font></td>
                    </tr>
                    <tr> 
                      <td align=right colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><br>
                        </font></td>
                    </tr>
                    </tbody> 
                  </table>
                </td>
              </tr>
              </tbody> 
            </table>
          </td>
        </tr>
        <tbody> 
        <tr> 
          <td height=24 noWrap>&nbsp;</td>
        </tr>
        </tbody> 
      </table>
      <font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
      <!-- START EXPERIENCE -->
      </font> 
      <table bgcolor=#999999 border=0 cellpadding=1 cellspacing=0 width=534>
        <tbody> 
        <tr> 
          <td> 
            <table bgcolor=#999999 border=0 cellpadding=0 cellspacing=0 
            width=533>
              <tbody> 
              <tr> 
                <td height=24><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#FFFFFF"><img border=0 height=1 
                  images/R1transparent_dot.gif" 
                  width=1 src="images/R1transparent_dot.gif"></font><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font><font color="#FFFFFF"><span 
            class=textWhtb>WORK EXPERIENCE</span></font></b></font></td>
              </tr>
              </tbody> 
            </table>
            <table bgcolor=#ffffff border=0 cellpadding=0 cellspacing=0 
            width=533>
              <tbody> 
              <tr> 
                <td bgcolor=#999999 colspan=6 height=1 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 
                  height=1 images/R1transparent_dot.gif" 
                  width=1></font></td>
              </tr>
              <tr> 
                <td height=24 noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=24 width=6 src="images/R1transparent_dot.gif" ></font></td>
                <td width=151>&nbsp;</td>
                <td colspan=2><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td align=right width="63"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
                  src="Jobline_fi_files/R1ViewCVSummary_files/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td height=20 noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=24 width=6 src="images/R1transparent_dot.gif" ></font></td>
                <td width="151" bgcolor="#CCCCCC"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Field</span></font></b></td>
                <td width="186" bgcolor="#CCCCCC"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Title</span></font></b></td>
                <td colspan=2 bgcolor="#CCCCCC"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Years</span></font></b></td>
                <td noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
                  images/R1transparent_dot.gif" 
              width=1 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td height=14 noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#FFFFFF width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span 
                class=texts>IT</span></font></td>
                <td bgcolor=#FFFFFF width="186"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Technician 
                      <br>
                      (use / support)</span></font></td>
                    <td bgcolor=#FFFFFF colspan=2><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><?php echo coppa_check(1, 1, 1991);?></font></td>
                    <td noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr bgcolor="#FFFFFF"> 
                <td width=7 height=14 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td width="151" bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span 
					class=texts>Media / Culture</span></font></td>
                <td width="186" bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>3D 
                  Modeler / Animator</span></font></td>
                    <td colspan=2 bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><span class=texts><?php echo coppa_check(1, 1, 1993);?></span></font></td>
                    <td width=7 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr>
                <td height=14 noWrap>&nbsp;</td>
                <td bgcolor=#FFFFFF><font size="2" face="Verdana, Arial, Helvetica, sans-serif">Business Owner <br>
                Web Lizards, LLC </font></td>
                <td bgcolor=#FFFFFF><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Technical Officer </font></td>
                <td bgcolor=#FFFFFF colspan=2><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><span class=texts><?php echo coppa_check(06, 01, 1998);?></span></font></td>
                <td noWrap>&nbsp;</td>
              </tr>
              <tr>
                <td height=14 noWrap>&nbsp;</td>
                <td bgcolor=#CCCCCC><font size="2" face="Verdana, Arial, Helvetica, sans-serif">Business Owner <br>
                Wap Oneline USA, LLC </font></td>
                <td bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2">CTO </font></td>
                <td bgcolor=#CCCCCC colspan=2><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><span class=texts><?php echo coppa_check(6, 1, 2000);?></span></font></td>
                <td noWrap>&nbsp;</td>
              </tr>
              <tr> 
                <td width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 width=1 src="images/R1transparent_dot.gif"></font></td>
                <td colspan=5 height=24 noWrap>&nbsp;</td>
              </tr>
              <tr> 
                <td colspan=6 height=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=6 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td height=24 noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 width=1 src="images/R1transparent_dot.gif"" ></font></td>
                <td bgcolor="#CCCCCC" width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><span class=texts><b>Previous/current<br>
                  </b></span><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><span class=texts><b>Employers</b></span></font></td>
                <td bgcolor="#CCCCCC" width="186"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td align=right colspan=2 bgcolor="#CCCCCC"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img src="images/R1transparent_dot.gif" border=0 height=1 width=1></font></td>
                <td noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td height=20 noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=24 width=6 src="images/R1transparent_dot.gif" ></font></td>
                <td width="151"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Job</span></font></b></td>
                <td width="186"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Employer</span></font></b></td>
                <td width="119"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>When</span></font></b></td>
                <td width="63"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Country</span></font></b></td>
                <td noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=12 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr>
                <td height=14 noWrap>&nbsp;</td>
                <td bgcolor=#CCCCCC nowrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>&nbsp;CTO <br>
                  &nbsp;(Founding member) </span></font></td>
                <td bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Wap Oneline USA, LLC, <br>
                  New Orleans, LA </span></font></td>
                <td bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>07/00
                      - present </span></font></td>
                <td bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>USA</span></font></td>
                <td noWrap>&nbsp;</td>
              </tr>
              <tr>
                <td height=14 noWrap>&nbsp;</td>
                <td valign="top" nowrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Description:</font></td>
                <td colspan="3"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Responsible for migrating the mobile content
                        technology from Europe in to Americas.</font><font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
                  <ul>
                    <li>Platform modifications for Americas</li>
                    <li>Server admin and maintenance</li>
                    <li>Database Admin and Maintenance </li>
                    <li>Project management</li>
                    <li>Development of new services </li>
                    <li>Integration with other entities </li>
                    <li>Content management</li>
                    </ul>
                        </font><br/></td>
                <td noWrap>&nbsp;</td>
              </tr>
              <tr>
                <td height=14 noWrap>&nbsp;</td>
                <td bgcolor=#CCCCCC nowrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>&nbsp;Technical Director<br>
                  &nbsp;(Founding Member)
</span></font></td>
                <td bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Web Lizards, LLC, <br>
                  New Orleans, LA </span></font></td>
                <td bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>07/98
                      - present </span></font></td>
                <td bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>USA</span></font></td>
                <td noWrap>&nbsp;</td>
              </tr>
              <tr>
                <td height=14 noWrap>&nbsp;</td>
                <td valign="top" nowrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Description:</font></td>
                <td colspan="3"><p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Responsible for Server administrative tasks. </font></p>
                  <font face="Verdana, Arial, Helvetica, sans-serif" size="2">
				  <ul>
                    <li>Dynamic web coding. </li>
                    <li>Customer Support. <br/>
                    </li>
                  </ul>
				  </font><br>				</td>
                <td noWrap>&nbsp;</td>
              </tr>
              <tr>
                <td height=14 noWrap>&nbsp;</td>
                <td bgcolor=#CCCCCC nowrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>&nbsp;3D
                      Modeler/Animator, <br>
                      &nbsp;Media technician.<br>
                      </span></font></td>
                <td bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>University
                      of New Orleans</span></font></td>
                <td bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>03/02
                      - ongoing </span></font></td>
                <td bgcolor=#CCCCCC><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>USA</span></font></td>
                <td noWrap>&nbsp;</td>
              </tr>
              <tr>
                <td height=14 noWrap>&nbsp;</td>
                <td nowrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Description:</font></td>
                <td colspan="3"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Please,
                      see descreption immediately below.</span></font></td>
                <td noWrap>&nbsp;</td>
              </tr>
              <tr> 
                <td height=14 noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#CCCCCC width="151" nowrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>&nbsp;Media 
                  technician<br>
                  &nbsp;(Student worker)</span></font></td>
                <td bgcolor=#CCCCCC width="186"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>University 
                  of New Orleans</span></font></td>
                <td bgcolor=#CCCCCC width="119"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>06/99
                       - 12/02 </span></font></td>
                <td bgcolor=#CCCCCC width="63"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>USA</span></font></td>
                <td noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#ffffff valign=top width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Description:</font></td>
                <td bgcolor=#ffffff colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><p>Research new technologies, recommend purchases.</p>
                  <p>Design, build and support educational Laboratories, for Non-linear edit stations. AVID MCXpress, Xpress for NT, Mac, Adobe Premiere with Miro DC30, Canopus DV Storm and Matrox RT 2000). Now obsoleted by modern systems, like Avid Xpress Pro, Avid Nitris etc... </p>
                  <p>Set up Computer Labs for 3D Modeling / Animation and Special F/X. Total of 110 computers including multiple different platforms. Set up and support networking and computers in media labs. Programs / Workstations technical support and training.</p>
                  <p>Create operational Rendering farm for 3D Studio Max and other 3D animation packages.</p>
                  <p>Build Full-body Motion Capture system and user training.<br>
                  </p></font></td>
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=12 noWrap>&nbsp;</td>
              </tr>
              <tr> 
                <td height=14 noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#CCCCCC width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>&nbsp;Academic 
                  Training<br>
                  &nbsp;3D Modeler / Animator</span></font></td>
                <td bgcolor=#CCCCCC width="186"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Moxie 
                  Media, Inc</span></font></td>
                <td bgcolor=#CCCCCC width="119"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>05/98 
                  - 06/99</span></font></td>
                <td bgcolor=#CCCCCC width="63"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>USA</span></font></td>
                <td noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#ffffff valign=top width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Description:</font></td>
                <td bgcolor=#ffffff colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>3D 
                  Modeling / animation. Web Design / Tech. Companys networking/administration.</span></font></td>
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=12 noWrap>&nbsp;</td>
              </tr>
              <tr> 
                <td height=14 noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#CCCCCC width="151" nowrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>&nbsp;Academic 
                  Training<br>
                  &nbsp;3D Modeler / Animator</span></font></td>
                <td bgcolor=#CCCCCC width="186"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>FirstNBC 
                  bank </span></font></td>
                <td bgcolor=#CCCCCC width="119"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>97/06 
                  - 98/05</span></font></td>
                <td bgcolor=#CCCCCC width="63"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>USA</span></font></td>
                <td noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#ffffff valign=top width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Description:</font></td>
                <td bgcolor=#ffffff colspan=3> 
                  <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>3D 
                    Modeling / animation for Internal training videos.<br>
                    Occasional involvement with PSA:s</span></font></p>                </td>
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=12 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=12 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td height=14 noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#CCCCCC width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>&nbsp;3D 
                  Modeling / &nbsp;Animation, <br>
                  &nbsp;Tech. Support</span></font></td>
                <td bgcolor=#CCCCCC width="186"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Isihei 
                  Oy</span></font></td>
                <td bgcolor=#CCCCCC width="119"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>92/01 
                  -</span></font></td>
                <td bgcolor=#CCCCCC width="63"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Finland</span></font></td>
                <td noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#ffffff valign=top width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Description:</font></td>
                <td bgcolor=#ffffff colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>3D 
                  Modeling / Animating. 3D Studio Max. Tech. support and networking. 
                  Other programs used: Adobe Photoshop, Adobe After F/X, Adobe 
                  Premiere</span></font></td>
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=12 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td height=14 noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#CCCCCC width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>&nbsp;Waiter, 
                  Bartender, <br>
                  &nbsp;Chef</span></font></td>
                <td bgcolor=#CCCCCC width="186"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Siipipyora 
                  OY<br>
                  (multiple branches)</span></font></td>
                <td bgcolor=#CCCCCC width="119"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>06/86 
                  - 08/90 </span></font></td>
                <td bgcolor=#CCCCCC width="63"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Finland</span></font></td>
                <td noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#ffffff valign=top width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Description:</font></td>
                <td bgcolor=#ffffff colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Normal 
                  duties of Chef, Waiter and Bartender </font></td>
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=12 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td height=14 noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#CCCCCC width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>&nbsp;Chef</span></font></td>
                <td bgcolor=#CCCCCC width="186"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Country 
                  of Finland, <br>
                  (Mandatory) military service</span></font></td>
                <td bgcolor=#CCCCCC width="119"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>01/87 
                  - 12/87 </span></font></td>
                <td bgcolor=#CCCCCC width="63"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Finland</span></font></td>
                <td noWrap width=7><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#ffffff valign=top width="151"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Description:</font></td>
                <td bgcolor=#ffffff colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Working 
                  as chef in the flagship of Finland, <br>
                  MineLayer MSS Pohjanmaa.</span></font></td>
                <td width="7"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=12 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td align=right colspan=6>&nbsp;</td>
              </tr>
              </tbody> 
            </table>
          </td>
        </tr>
        </tbody> 
      </table>
      <font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
      <!-- END EXPERIENCE -->
      </font> 
      <table cellpadding=0 cellspacing=0 height=24 width=533>
        <tbody> 
        <tr> 
          <td height=24 noWrap>&nbsp;</td>
        </tr>
        </tbody> 
      </table>
      <font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
      <!-- START EDUCATION -->
      </font> 
      <table bgcolor=#999999 border=0 cellpadding=1 cellspacing=0 width=534>
        <tbody> 
        <tr> 
          <td> 
            <table bgcolor=#999999 border=0 cellpadding=0 cellspacing=0 
            width=533>
              <tbody> 
              <tr> 
                <td height=24><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><b><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"><span 
            class=textWhtb>EDUCATION</span></b></font></td>
              </tr>
              </tbody> 
            </table>
            <table bgcolor=#ffffff border=0 cellpadding=0 cellspacing=0 
            width=533>
              <tbody> 
              <tr> 
                <td bgcolor=#999999 colspan=6 height=1 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 
                  height=1 images/R1transparent_dot.gif" 
                  width=1></font></td>
              </tr>
              <tr> 
                <td height=24 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=24 width=6 src="images/R1transparent_dot.gif"></font></td>
                <td colspan=4 bgcolor="#CCCCCC"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><span 
                  class=texts><b>College</b></span></font></td>
                <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td height=20 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=24 width=6 src="images/R1transparent_dot.gif" ></font></td>
                <td width=150><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Field</font></b></td>
                <td width="169"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Degree</span></font></b></td>
                <td width="123"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Institution</span></font></b></td>
                <td width="79"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Graduated</span></font></b></td>
                <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td height=14 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#CCCCCC width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Communications</span></font></td>
                <td bgcolor=#CCCCCC width="169"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Bachelor's 
                  Degree</span></font></td>
                <td bgcolor=#CCCCCC width="123"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>University 
                  of New Orleans</span></font></td>
                    <td bgcolor=#CCCCCC width="79"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>May 
                      2002 </span></font></td>
                <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td width="6"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#ffffff valign=top width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span 
                class=texts>Description</span></font></td>
                    <td bgcolor=#ffffff colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Graduated 
                      in May 2002. Drama &amp; Communications dept.<br>
                  Emphasis in 3D Animation and Special F/X for TV, Video and Film.</span></font></td>
                <td width="6"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=6 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td height=24 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=24 width=6 src="images/R1transparent_dot.gif"></font></td>
                <td colspan=4 bgcolor="#CCCCCC"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><span class=texts><b>Other 
                  Education and Courses</b></span></font></td>
                <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td height=20 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=24 width=6 src="images/R1transparent_dot.gif" ></font></td>
                <td width=150><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Field</span></font></b></td>
                <td width="169"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>School</span></font></b></td>
                <td colspan=2><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>&nbsp;When</span></font></b></td>
                <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td height=14 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#CCCCCC width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Restaurant 
                  personel</span></font></td>
                <td bgcolor=#CCCCCC width="169"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Technical 
                  school of Orimattila</span></font></td>
                <td bgcolor=#CCCCCC colspan=2><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span 
                class=texts>&nbsp;08/83 - 05/85 </span></font></td>
                <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td width="6"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#ffffff valign=top width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span 
                class=texts>Description:</span></font></td>
                <td bgcolor=#ffffff colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Trainig 
                  for work in the kitchen</span></font></td>
                <td width="6"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=6 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td height=14 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#CCCCCC width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Basic 
                  School</span></font></td>
                <td bgcolor=#CCCCCC width="169"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Elementary- 
                  and Junior high school of Orimattila</span></font></td>
                <td bgcolor=#CCCCCC colspan=2><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span 
                class=texts>&nbsp;08/73 - 05/83 </span></font></td>
                <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td width="6"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#ffffff valign=top width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span 
                class=texts>Description:</span></font></td>
                <td bgcolor=#ffffff colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Mandatory 
                  school</span></font></td>
                <td width="6"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=6 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td height=14 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#CCCCCC width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Chef</span></font></td>
                <td bgcolor=#CCCCCC width="169"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Naval 
                  institute of Kotka</span></font></td>
                <td bgcolor=#CCCCCC colspan=2><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span 
                class=texts>&nbsp;08/85 - 05/86 </span></font></td>
                <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td width="6"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#ffffff valign=top width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span 
                class=texts>Description:</span></font></td>
                <td bgcolor=#ffffff colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Training 
                  to work as a chef on the ship</span></font></td>
                <td width="6"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=6 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td height=14 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#CCCCCC width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Private 
                  pilot</span></font></td>
                <td bgcolor=#CCCCCC width="169"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Mountain 
                  Flyers</span></font></td>
                <td bgcolor=#CCCCCC colspan=2><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span 
                class=texts>&nbsp;06/95 - 06/96 </span></font></td>
                <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
              </tr>
              <tr> 
                <td width="6"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" width=1></font></td>
                <td bgcolor=#ffffff valign=top width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span 
                class=texts>Description:</span></font></td>
                <td bgcolor=#ffffff colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Private 
                  Pilot license</span></font></td>
                <td width="6"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
                <td colspan=6 height=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=6 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
              </tr>
              <tr> 
               <td align=right colspan=3><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><br>
                </font></td>

              </tr>
              </tbody> 
            </table>
          </td>
        </tr>
        </tbody> 
      </table>
      <font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
      <!-- END EDUCATION -->
      <!-- START KNOWLEDGE -->
      </font> <br>
      <table cellpadding=0 cellspacing=0 height=24 width=533>
        <tr> 
          <td height=24 noWrap> 
            <table bgcolor=#999999 border=0 cellpadding=1 cellspacing=0 width=534>
              <tbody> 
              <tr> 
                <td> 
                  <table bgcolor=#999999 border=0 cellpadding=0 cellspacing=0 
            width=533>
                    <tbody> 
                    <tr> 
                      <td height=24><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 
                  images/R1transparent_dot.gif" 
                  width=1><span 
            class=textWhtb><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font><font color="#FFFFFF">MISC</font></b></span></font></td>
                    </tr>
                    </tbody> 
                  </table>
                  <table bgcolor=#ffffff border=0 cellpadding=0 cellspacing=0 
            width=533>
                    <tbody> 
                    <tr> 
                      <td bgcolor=#999999 colspan=3 height=1 noWrap><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 
                  height=1 images/R1transparent_dot.gif" 
                  width=1></font></td>
                    </tr>
                    <tr> 
                      <td height=24 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
                  images/R1transparent_dot.gif" width=1 src="Jobline_fi_files/R1ViewCVSummary_files/R1transparent_dot.gif"></font></td>
                      <td bgcolor="#CCCCCC"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><span class=texts><b>Computer 
                        Skills in general</b></span></font></td>
                      <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
                  images/R1transparent_dot.gif" 
              width=1 src="Jobline_fi_files/R1ViewCVSummary_files/R1transparent_dot.gif"></font></td>
                    </tr>
                    <tr> 
                      <td noWrap width=4><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=12 width=4 src="images/R1transparent_dot.gif"></font></td>
                      <td> 
                        <table border=0 cellpadding=3 cellspacing=0 width="514">
                          <tbody> 
                          <tr> 
                            <td> 
                              <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts>Operating 
                                      systems:<br>
                                      Windows (all variants), Linux (multiple Distros), <br>
                                      MAC (I know enough to stay away) <br>
                                      </span></font><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><span class=texts><br>
                                      Networking / Servers:<br>
                                      TCP/IP, Firewalls, Switches, Routing</span></font><font face="Verdana, Arial, Helvetica, sans-serif" size="2">, Mail.<br>
                                      Windows  Server, Linux, Apache,
                                       Real Server,  MySQL, MS SQL.</font></p>
                                    <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Programming:<br>
                                      Dynamic web development with  
                                      .php, .css, + others if needed </font></p>
                                    </td>
                          </tr>
                          </tbody> 
                        </table>
                      </td>
                      <td noWrap width=4><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
               width=1 src="Jobline_fi_files/R1ViewCVSummary_files/R1transparent_dot.gif"></font></td>
                    </tr>
                    <tr> 
                      <td colspan=3 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=1 
                  images/R1transparent_dot.gif" 
              width=1></font></td>
                    </tr>
                    <tr> 
                      <td height=24 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=24 width=6 src="images/R1transparent_dot.gif"></font></td>
                      <td bgcolor="#CCCCCC"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><span class=texts><b>Software 
                        skills </b></span></font></td>
                      <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
                    </tr>
                    <tr> 
                      <td noWrap width=4><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=12 width=4 src="images/R1transparent_dot.gif" ></font></td>
                      <td> 
                        <table border=0 cellpadding=3 cellspacing=0 width="513">
                          <tbody> 
                          <tr> 
                            <td> 
                              <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Adobe:<br>
                                Photoshop, Premiere, After Effects, GoLive, Illustrator, 
                                Indesign Image Ready, Acrobat.</font></p>
                              <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Macromedia:<br>
                                Dreamweaver, Ultradev, Freehand, Flash, Fireworks, 
                                Director. </font></p>
                              <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Discreet:<br>
                                3D Studio MaX, Combustion, Edit*</font></p>
                              <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">AVID:<br>
                                MCXpress NT, Xpress (mac), Xpress Pro DV.</font></p>
                              <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Microsoft:<br>
                                Office, Windows Media Tools, Many Others.</font></p>
                              <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Others:<br>
                                Maya, EVa, Director Sequencer, MAC RT, RealMedia, 
                                Cleaner, Shake,<br>
                                + many more.</font></p>
                            </td>
                          </tr>
                          </tbody> 
                        </table>
                      </td>
                      <td noWrap width=4><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=12 width=4
                  src="images/R1transparent_dot.gif" 
              ></font></td>
                    </tr>
                    <tr> 
                      <td height=24 noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=24 width=6 src="images/R1transparent_dot.gif"></font></td>
                      <td bgcolor="#CCCCCC"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#FFFFFF"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></b><span class=texts><b>Awards 
                        / Achievements</b></span></font></td>
                      <td noWrap width=6><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=10 width=6 src="images/R1transparent_dot.gif"></font></td>
                    </tr>
                    <tr> 
                      <td noWrap width=4><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=12 width=4 src="images/R1transparent_dot.gif" ></font></td>
                      <td> 
                        <table border=0 cellpadding=3 cellspacing=0 width="513">
                          <tbody> 
                          <tr> 
                            <td> 
                              <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">20?? AT&amp;T Developer of the month (mcmwap.com) <br>
                                1999 
                                Telly Award - 625 St. Charles<br>
                                </font><font face="Verdana, Arial, Helvetica, sans-serif" size="2">1997 
                                DV Magazine, Media Masters - Student Project 2nd 
                                place<br>
                                </font><font face="Verdana, Arial, Helvetica, sans-serif" size="2">KOFF, 
                                Advertizing Ideas - 2nd place</font></p>
                              <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Pepsodent 
                                Kids - Animation for Commercial<br>
                                YLE ( Finnish National Radio ) - Animation for 
                                Multimedia CD-rom<br>
                                AXE - Animation for Commercial<br>
                                Maxi Fun - Product Animation for International 
                                Trade Show and Distribution<br>
                                Back to the Blue, PSA - 3D logo<br>
                                UPS, internal video - Logo Animation</font></p>
                              </td>
                          </tr>
                          </tbody> 
                        </table>
                      </td>
                      <td noWrap width=4><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><img border=0 height=12 width=4
                  src="images/R1transparent_dot.gif" 
              ></font></td>
                    </tr>
                    <tr> 

                    </tr>
                    <tr> 
                      <td align=right colspan=3>&nbsp;</td>
                    </tr>
                    </tbody> 
                  </table>
                </td>
              </tr>
              </tbody> 
            </table>
          </td>
        </tr>
        <tbody> 
        <tr> 
          <td height=24 noWrap>&nbsp;</td>
        </tr>
        </tbody> 
      </table>
      <table bgcolor=#999999 border=0 cellpadding=1 cellspacing=0 width=100%>
        <tbody> 
        <tr> 
          <td>&nbsp; </td>
        </tr>
        </tbody> 
      </table>
      
    </td>
  </tr>
  </tbody>
</table>
</body>
</html>
